default:
  image: java:alpine
  before_script:
    - apk update && apk add --update python3 curl tar bash bash-doc bash-completion wget apache-ant zip
  
job:
  script:
    - mkdir /tmp
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-linux-x86_64.zip -P /tmp
    - unzip /temp/protoc-3.11.3-linux-x86_64.zip -d /temp
    - export PATH=/tmp/bin:$PATH
    - mvn install -Dgpg.skip
