default:
  image: java:alpine
  before_script:
    - apk update && apk add --update python3 curl tar bash bash-doc bash-completion wget apache-ant zip
  
job:
  script:
    - mkdir /protoc
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-linux-x86_64.zip -P /protoc
    - unzip /protoc/protoc-3.11.3-linux-x86_64.zip -d /protoc
    - export PATH=/protoc/bin:$PATH
    - mvn install -Dgpg.skip
