// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface AvailableSubmissionsPerSubmissionTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.AvailableSubmissionsPerSubmissionType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 submissions_left = 1;</code>
   * @return The submissionsLeft.
   */
  int getSubmissionsLeft();

  /**
   * <code>int32 min_player_level = 2;</code>
   * @return The minPlayerLevel.
   */
  int getMinPlayerLevel();

  /**
   * <code>bool is_feature_enabled = 3;</code>
   * @return The isFeatureEnabled.
   */
  boolean getIsFeatureEnabled();

  /**
   * <code>int64 time_window_for_submissions_limit_ms = 4;</code>
   * @return The timeWindowForSubmissionsLimitMs.
   */
  long getTimeWindowForSubmissionsLimitMs();

  /**
   * <code>int32 max_poi_distance_in_meters = 5;</code>
   * @return The maxPoiDistanceInMeters.
   */
  int getMaxPoiDistanceInMeters();

  /**
   * <code>repeated string blacklisted_os = 6;</code>
   * @return A list containing the blacklistedOs.
   */
  java.util.List<java.lang.String>
      getBlacklistedOsList();
  /**
   * <code>repeated string blacklisted_os = 6;</code>
   * @return The count of blacklistedOs.
   */
  int getBlacklistedOsCount();
  /**
   * <code>repeated string blacklisted_os = 6;</code>
   * @param index The index of the element to return.
   * @return The blacklistedOs at the given index.
   */
  java.lang.String getBlacklistedOs(int index);
  /**
   * <code>repeated string blacklisted_os = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the blacklistedOs at the given index.
   */
  com.google.protobuf.ByteString
      getBlacklistedOsBytes(int index);

  /**
   * <code>repeated string blacklisted_device_id = 7;</code>
   * @return A list containing the blacklistedDeviceId.
   */
  java.util.List<java.lang.String>
      getBlacklistedDeviceIdList();
  /**
   * <code>repeated string blacklisted_device_id = 7;</code>
   * @return The count of blacklistedDeviceId.
   */
  int getBlacklistedDeviceIdCount();
  /**
   * <code>repeated string blacklisted_device_id = 7;</code>
   * @param index The index of the element to return.
   * @return The blacklistedDeviceId at the given index.
   */
  java.lang.String getBlacklistedDeviceId(int index);
  /**
   * <code>repeated string blacklisted_device_id = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the blacklistedDeviceId at the given index.
   */
  com.google.protobuf.ByteString
      getBlacklistedDeviceIdBytes(int index);

  /**
   * <code>bool is_whitelisted_user = 8;</code>
   * @return The isWhitelistedUser.
   */
  boolean getIsWhitelistedUser();
}
