// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface BattleQuestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.BattleQuestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string battle_id = 1;</code>
   * @return A list containing the battleId.
   */
  java.util.List<java.lang.String>
      getBattleIdList();
  /**
   * <code>repeated string battle_id = 1;</code>
   * @return The count of battleId.
   */
  int getBattleIdCount();
  /**
   * <code>repeated string battle_id = 1;</code>
   * @param index The index of the element to return.
   * @return The battleId at the given index.
   */
  java.lang.String getBattleId(int index);
  /**
   * <code>repeated string battle_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the battleId at the given index.
   */
  com.google.protobuf.ByteString
      getBattleIdBytes(int index);
}
