// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface ChangePokemonFormProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.ChangePokemonFormProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 pokemon_id = 1;</code>
   * @return The pokemonId.
   */
  long getPokemonId();

  /**
   * <code>.POGOProtos.Rpc.PokemonDisplayProto.Form target_form = 2;</code>
   * @return The enum numeric value on the wire for targetForm.
   */
  int getTargetFormValue();
  /**
   * <code>.POGOProtos.Rpc.PokemonDisplayProto.Form target_form = 2;</code>
   * @return The targetForm.
   */
  POGOProtos.Rpc.PokemonDisplayProto.Form getTargetForm();
}
