// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface ChangePokemonFormOutProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.ChangePokemonFormOutProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.ChangePokemonFormOutProto.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.POGOProtos.Rpc.ChangePokemonFormOutProto.Result result = 1;</code>
   * @return The result.
   */
  POGOProtos.Rpc.ChangePokemonFormOutProto.Result getResult();

  /**
   * <code>.POGOProtos.Rpc.PokemonProto changed_pokemon = 2;</code>
   * @return Whether the changedPokemon field is set.
   */
  boolean hasChangedPokemon();
  /**
   * <code>.POGOProtos.Rpc.PokemonProto changed_pokemon = 2;</code>
   * @return The changedPokemon.
   */
  POGOProtos.Rpc.PokemonProto getChangedPokemon();
  /**
   * <code>.POGOProtos.Rpc.PokemonProto changed_pokemon = 2;</code>
   */
  POGOProtos.Rpc.PokemonProtoOrBuilder getChangedPokemonOrBuilder();

  /**
   * <code>int32 exp_awarded = 3;</code>
   * @return The expAwarded.
   */
  int getExpAwarded();

  /**
   * <code>int32 candy_awarded = 4;</code>
   * @return The candyAwarded.
   */
  int getCandyAwarded();
}
