// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto}
 */
public final class ChooseGlobalTicketedEventVariantProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)
    ChooseGlobalTicketedEventVariantProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChooseGlobalTicketedEventVariantProto.newBuilder() to construct.
  private ChooseGlobalTicketedEventVariantProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChooseGlobalTicketedEventVariantProto() {
    targetVariant_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChooseGlobalTicketedEventVariantProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChooseGlobalTicketedEventVariantProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            targetVariant_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_ChooseGlobalTicketedEventVariantProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_ChooseGlobalTicketedEventVariantProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.class, POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.Builder.class);
  }

  public static final int TARGET_VARIANT_FIELD_NUMBER = 1;
  private int targetVariant_;
  /**
   * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
   * @return The enum numeric value on the wire for targetVariant.
   */
  @java.lang.Override public int getTargetVariantValue() {
    return targetVariant_;
  }
  /**
   * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
   * @return The targetVariant.
   */
  @java.lang.Override public POGOProtos.Rpc.HoloBadgeType getTargetVariant() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.HoloBadgeType result = POGOProtos.Rpc.HoloBadgeType.valueOf(targetVariant_);
    return result == null ? POGOProtos.Rpc.HoloBadgeType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (targetVariant_ != POGOProtos.Rpc.HoloBadgeType.BADGE_UNSET.getNumber()) {
      output.writeEnum(1, targetVariant_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (targetVariant_ != POGOProtos.Rpc.HoloBadgeType.BADGE_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, targetVariant_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto other = (POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto) obj;

    if (targetVariant_ != other.targetVariant_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_VARIANT_FIELD_NUMBER;
    hash = (53 * hash) + targetVariant_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)
      POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_ChooseGlobalTicketedEventVariantProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_ChooseGlobalTicketedEventVariantProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.class, POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.Builder.class);
    }

    // Construct using POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      targetVariant_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_ChooseGlobalTicketedEventVariantProto_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto getDefaultInstanceForType() {
      return POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto build() {
      POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto buildPartial() {
      POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto result = new POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto(this);
      result.targetVariant_ = targetVariant_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto) {
        return mergeFrom((POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto other) {
      if (other == POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto.getDefaultInstance()) return this;
      if (other.targetVariant_ != 0) {
        setTargetVariantValue(other.getTargetVariantValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int targetVariant_ = 0;
    /**
     * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
     * @return The enum numeric value on the wire for targetVariant.
     */
    @java.lang.Override public int getTargetVariantValue() {
      return targetVariant_;
    }
    /**
     * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
     * @param value The enum numeric value on the wire for targetVariant to set.
     * @return This builder for chaining.
     */
    public Builder setTargetVariantValue(int value) {
      
      targetVariant_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
     * @return The targetVariant.
     */
    @java.lang.Override
    public POGOProtos.Rpc.HoloBadgeType getTargetVariant() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.HoloBadgeType result = POGOProtos.Rpc.HoloBadgeType.valueOf(targetVariant_);
      return result == null ? POGOProtos.Rpc.HoloBadgeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
     * @param value The targetVariant to set.
     * @return This builder for chaining.
     */
    public Builder setTargetVariant(POGOProtos.Rpc.HoloBadgeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      targetVariant_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.HoloBadgeType target_variant = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetVariant() {
      
      targetVariant_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto)
  private static final POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto();
  }

  public static POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChooseGlobalTicketedEventVariantProto>
      PARSER = new com.google.protobuf.AbstractParser<ChooseGlobalTicketedEventVariantProto>() {
    @java.lang.Override
    public ChooseGlobalTicketedEventVariantProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChooseGlobalTicketedEventVariantProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChooseGlobalTicketedEventVariantProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChooseGlobalTicketedEventVariantProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.ChooseGlobalTicketedEventVariantProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

