// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface DummyDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.DummyDataProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   * @return Whether the dummyPokemon field is set.
   */
  boolean hasDummyPokemon();
  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   * @return The dummyPokemon.
   */
  POGOProtos.Rpc.PokemonProto getDummyPokemon();
  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   */
  POGOProtos.Rpc.PokemonProtoOrBuilder getDummyPokemonOrBuilder();
}
