// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.DummyDataProto}
 */
public final class DummyDataProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.DummyDataProto)
    DummyDataProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DummyDataProto.newBuilder() to construct.
  private DummyDataProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DummyDataProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DummyDataProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DummyDataProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            POGOProtos.Rpc.PokemonProto.Builder subBuilder = null;
            if (dummyPokemon_ != null) {
              subBuilder = dummyPokemon_.toBuilder();
            }
            dummyPokemon_ = input.readMessage(POGOProtos.Rpc.PokemonProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dummyPokemon_);
              dummyPokemon_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_DummyDataProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_DummyDataProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.DummyDataProto.class, POGOProtos.Rpc.DummyDataProto.Builder.class);
  }

  public static final int DUMMY_POKEMON_FIELD_NUMBER = 1;
  private POGOProtos.Rpc.PokemonProto dummyPokemon_;
  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   * @return Whether the dummyPokemon field is set.
   */
  @java.lang.Override
  public boolean hasDummyPokemon() {
    return dummyPokemon_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   * @return The dummyPokemon.
   */
  @java.lang.Override
  public POGOProtos.Rpc.PokemonProto getDummyPokemon() {
    return dummyPokemon_ == null ? POGOProtos.Rpc.PokemonProto.getDefaultInstance() : dummyPokemon_;
  }
  /**
   * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.PokemonProtoOrBuilder getDummyPokemonOrBuilder() {
    return getDummyPokemon();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dummyPokemon_ != null) {
      output.writeMessage(1, getDummyPokemon());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dummyPokemon_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDummyPokemon());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.DummyDataProto)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.DummyDataProto other = (POGOProtos.Rpc.DummyDataProto) obj;

    if (hasDummyPokemon() != other.hasDummyPokemon()) return false;
    if (hasDummyPokemon()) {
      if (!getDummyPokemon()
          .equals(other.getDummyPokemon())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDummyPokemon()) {
      hash = (37 * hash) + DUMMY_POKEMON_FIELD_NUMBER;
      hash = (53 * hash) + getDummyPokemon().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.DummyDataProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.DummyDataProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.DummyDataProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.DummyDataProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.DummyDataProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.DummyDataProto)
      POGOProtos.Rpc.DummyDataProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_DummyDataProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_DummyDataProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.DummyDataProto.class, POGOProtos.Rpc.DummyDataProto.Builder.class);
    }

    // Construct using POGOProtos.Rpc.DummyDataProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dummyPokemonBuilder_ == null) {
        dummyPokemon_ = null;
      } else {
        dummyPokemon_ = null;
        dummyPokemonBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_DummyDataProto_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.DummyDataProto getDefaultInstanceForType() {
      return POGOProtos.Rpc.DummyDataProto.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.DummyDataProto build() {
      POGOProtos.Rpc.DummyDataProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.DummyDataProto buildPartial() {
      POGOProtos.Rpc.DummyDataProto result = new POGOProtos.Rpc.DummyDataProto(this);
      if (dummyPokemonBuilder_ == null) {
        result.dummyPokemon_ = dummyPokemon_;
      } else {
        result.dummyPokemon_ = dummyPokemonBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.DummyDataProto) {
        return mergeFrom((POGOProtos.Rpc.DummyDataProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.DummyDataProto other) {
      if (other == POGOProtos.Rpc.DummyDataProto.getDefaultInstance()) return this;
      if (other.hasDummyPokemon()) {
        mergeDummyPokemon(other.getDummyPokemon());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.DummyDataProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.DummyDataProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private POGOProtos.Rpc.PokemonProto dummyPokemon_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PokemonProto, POGOProtos.Rpc.PokemonProto.Builder, POGOProtos.Rpc.PokemonProtoOrBuilder> dummyPokemonBuilder_;
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     * @return Whether the dummyPokemon field is set.
     */
    public boolean hasDummyPokemon() {
      return dummyPokemonBuilder_ != null || dummyPokemon_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     * @return The dummyPokemon.
     */
    public POGOProtos.Rpc.PokemonProto getDummyPokemon() {
      if (dummyPokemonBuilder_ == null) {
        return dummyPokemon_ == null ? POGOProtos.Rpc.PokemonProto.getDefaultInstance() : dummyPokemon_;
      } else {
        return dummyPokemonBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public Builder setDummyPokemon(POGOProtos.Rpc.PokemonProto value) {
      if (dummyPokemonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dummyPokemon_ = value;
        onChanged();
      } else {
        dummyPokemonBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public Builder setDummyPokemon(
        POGOProtos.Rpc.PokemonProto.Builder builderForValue) {
      if (dummyPokemonBuilder_ == null) {
        dummyPokemon_ = builderForValue.build();
        onChanged();
      } else {
        dummyPokemonBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public Builder mergeDummyPokemon(POGOProtos.Rpc.PokemonProto value) {
      if (dummyPokemonBuilder_ == null) {
        if (dummyPokemon_ != null) {
          dummyPokemon_ =
            POGOProtos.Rpc.PokemonProto.newBuilder(dummyPokemon_).mergeFrom(value).buildPartial();
        } else {
          dummyPokemon_ = value;
        }
        onChanged();
      } else {
        dummyPokemonBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public Builder clearDummyPokemon() {
      if (dummyPokemonBuilder_ == null) {
        dummyPokemon_ = null;
        onChanged();
      } else {
        dummyPokemon_ = null;
        dummyPokemonBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public POGOProtos.Rpc.PokemonProto.Builder getDummyPokemonBuilder() {
      
      onChanged();
      return getDummyPokemonFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    public POGOProtos.Rpc.PokemonProtoOrBuilder getDummyPokemonOrBuilder() {
      if (dummyPokemonBuilder_ != null) {
        return dummyPokemonBuilder_.getMessageOrBuilder();
      } else {
        return dummyPokemon_ == null ?
            POGOProtos.Rpc.PokemonProto.getDefaultInstance() : dummyPokemon_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.PokemonProto dummy_pokemon = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.PokemonProto, POGOProtos.Rpc.PokemonProto.Builder, POGOProtos.Rpc.PokemonProtoOrBuilder> 
        getDummyPokemonFieldBuilder() {
      if (dummyPokemonBuilder_ == null) {
        dummyPokemonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.PokemonProto, POGOProtos.Rpc.PokemonProto.Builder, POGOProtos.Rpc.PokemonProtoOrBuilder>(
                getDummyPokemon(),
                getParentForChildren(),
                isClean());
        dummyPokemon_ = null;
      }
      return dummyPokemonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.DummyDataProto)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.DummyDataProto)
  private static final POGOProtos.Rpc.DummyDataProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.DummyDataProto();
  }

  public static POGOProtos.Rpc.DummyDataProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DummyDataProto>
      PARSER = new com.google.protobuf.AbstractParser<DummyDataProto>() {
    @java.lang.Override
    public DummyDataProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DummyDataProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DummyDataProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DummyDataProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.DummyDataProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

