// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.FormChangeProto}
 */
public final class FormChangeProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.FormChangeProto)
    FormChangeProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FormChangeProto.newBuilder() to construct.
  private FormChangeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FormChangeProto() {
    availableForm_ = java.util.Collections.emptyList();
    itemCost_ = 0;
    questRequirement_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FormChangeProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FormChangeProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              availableForm_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            availableForm_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                availableForm_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              availableForm_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 16: {

            candyCost_ = input.readInt32();
            break;
          }
          case 24: {

            stardustCost_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            itemCost_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              questRequirement_ = new java.util.ArrayList<POGOProtos.Rpc.EvolutionQuestInfoProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            questRequirement_.add(
                input.readMessage(POGOProtos.Rpc.EvolutionQuestInfoProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        availableForm_ = java.util.Collections.unmodifiableList(availableForm_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        questRequirement_ = java.util.Collections.unmodifiableList(questRequirement_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FormChangeProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FormChangeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.FormChangeProto.class, POGOProtos.Rpc.FormChangeProto.Builder.class);
  }

  public static final int AVAILABLE_FORM_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> availableForm_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, POGOProtos.Rpc.PokemonDisplayProto.Form> availableForm_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, POGOProtos.Rpc.PokemonDisplayProto.Form>() {
            public POGOProtos.Rpc.PokemonDisplayProto.Form convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              POGOProtos.Rpc.PokemonDisplayProto.Form result = POGOProtos.Rpc.PokemonDisplayProto.Form.valueOf(from);
              return result == null ? POGOProtos.Rpc.PokemonDisplayProto.Form.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
   * @return A list containing the availableForm.
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.PokemonDisplayProto.Form> getAvailableFormList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, POGOProtos.Rpc.PokemonDisplayProto.Form>(availableForm_, availableForm_converter_);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
   * @return The count of availableForm.
   */
  @java.lang.Override
  public int getAvailableFormCount() {
    return availableForm_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
   * @param index The index of the element to return.
   * @return The availableForm at the given index.
   */
  @java.lang.Override
  public POGOProtos.Rpc.PokemonDisplayProto.Form getAvailableForm(int index) {
    return availableForm_converter_.convert(availableForm_.get(index));
  }
  /**
   * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
   * @return A list containing the enum numeric values on the wire for availableForm.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getAvailableFormValueList() {
    return availableForm_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of availableForm at the given index.
   */
  @java.lang.Override
  public int getAvailableFormValue(int index) {
    return availableForm_.get(index);
  }
  private int availableFormMemoizedSerializedSize;

  public static final int CANDY_COST_FIELD_NUMBER = 2;
  private int candyCost_;
  /**
   * <code>int32 candy_cost = 2;</code>
   * @return The candyCost.
   */
  @java.lang.Override
  public int getCandyCost() {
    return candyCost_;
  }

  public static final int STARDUST_COST_FIELD_NUMBER = 3;
  private int stardustCost_;
  /**
   * <code>int32 stardust_cost = 3;</code>
   * @return The stardustCost.
   */
  @java.lang.Override
  public int getStardustCost() {
    return stardustCost_;
  }

  public static final int ITEM_COST_FIELD_NUMBER = 4;
  private int itemCost_;
  /**
   * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
   * @return The enum numeric value on the wire for itemCost.
   */
  @java.lang.Override public int getItemCostValue() {
    return itemCost_;
  }
  /**
   * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
   * @return The itemCost.
   */
  @java.lang.Override public POGOProtos.Rpc.Item getItemCost() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.Item result = POGOProtos.Rpc.Item.valueOf(itemCost_);
    return result == null ? POGOProtos.Rpc.Item.UNRECOGNIZED : result;
  }

  public static final int QUEST_REQUIREMENT_FIELD_NUMBER = 5;
  private java.util.List<POGOProtos.Rpc.EvolutionQuestInfoProto> questRequirement_;
  /**
   * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.EvolutionQuestInfoProto> getQuestRequirementList() {
    return questRequirement_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder> 
      getQuestRequirementOrBuilderList() {
    return questRequirement_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
   */
  @java.lang.Override
  public int getQuestRequirementCount() {
    return questRequirement_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.EvolutionQuestInfoProto getQuestRequirement(int index) {
    return questRequirement_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder getQuestRequirementOrBuilder(
      int index) {
    return questRequirement_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getAvailableFormList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(availableFormMemoizedSerializedSize);
    }
    for (int i = 0; i < availableForm_.size(); i++) {
      output.writeEnumNoTag(availableForm_.get(i));
    }
    if (candyCost_ != 0) {
      output.writeInt32(2, candyCost_);
    }
    if (stardustCost_ != 0) {
      output.writeInt32(3, stardustCost_);
    }
    if (itemCost_ != POGOProtos.Rpc.Item.ITEM_UNKNOWN.getNumber()) {
      output.writeEnum(4, itemCost_);
    }
    for (int i = 0; i < questRequirement_.size(); i++) {
      output.writeMessage(5, questRequirement_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < availableForm_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(availableForm_.get(i));
      }
      size += dataSize;
      if (!getAvailableFormList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }availableFormMemoizedSerializedSize = dataSize;
    }
    if (candyCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, candyCost_);
    }
    if (stardustCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, stardustCost_);
    }
    if (itemCost_ != POGOProtos.Rpc.Item.ITEM_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, itemCost_);
    }
    for (int i = 0; i < questRequirement_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, questRequirement_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.FormChangeProto)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.FormChangeProto other = (POGOProtos.Rpc.FormChangeProto) obj;

    if (!availableForm_.equals(other.availableForm_)) return false;
    if (getCandyCost()
        != other.getCandyCost()) return false;
    if (getStardustCost()
        != other.getStardustCost()) return false;
    if (itemCost_ != other.itemCost_) return false;
    if (!getQuestRequirementList()
        .equals(other.getQuestRequirementList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAvailableFormCount() > 0) {
      hash = (37 * hash) + AVAILABLE_FORM_FIELD_NUMBER;
      hash = (53 * hash) + availableForm_.hashCode();
    }
    hash = (37 * hash) + CANDY_COST_FIELD_NUMBER;
    hash = (53 * hash) + getCandyCost();
    hash = (37 * hash) + STARDUST_COST_FIELD_NUMBER;
    hash = (53 * hash) + getStardustCost();
    hash = (37 * hash) + ITEM_COST_FIELD_NUMBER;
    hash = (53 * hash) + itemCost_;
    if (getQuestRequirementCount() > 0) {
      hash = (37 * hash) + QUEST_REQUIREMENT_FIELD_NUMBER;
      hash = (53 * hash) + getQuestRequirementList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.FormChangeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FormChangeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.FormChangeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.FormChangeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.FormChangeProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.FormChangeProto)
      POGOProtos.Rpc.FormChangeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FormChangeProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FormChangeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.FormChangeProto.class, POGOProtos.Rpc.FormChangeProto.Builder.class);
    }

    // Construct using POGOProtos.Rpc.FormChangeProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQuestRequirementFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      availableForm_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      candyCost_ = 0;

      stardustCost_ = 0;

      itemCost_ = 0;

      if (questRequirementBuilder_ == null) {
        questRequirement_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        questRequirementBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_FormChangeProto_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.FormChangeProto getDefaultInstanceForType() {
      return POGOProtos.Rpc.FormChangeProto.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.FormChangeProto build() {
      POGOProtos.Rpc.FormChangeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.FormChangeProto buildPartial() {
      POGOProtos.Rpc.FormChangeProto result = new POGOProtos.Rpc.FormChangeProto(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        availableForm_ = java.util.Collections.unmodifiableList(availableForm_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.availableForm_ = availableForm_;
      result.candyCost_ = candyCost_;
      result.stardustCost_ = stardustCost_;
      result.itemCost_ = itemCost_;
      if (questRequirementBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          questRequirement_ = java.util.Collections.unmodifiableList(questRequirement_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.questRequirement_ = questRequirement_;
      } else {
        result.questRequirement_ = questRequirementBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.FormChangeProto) {
        return mergeFrom((POGOProtos.Rpc.FormChangeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.FormChangeProto other) {
      if (other == POGOProtos.Rpc.FormChangeProto.getDefaultInstance()) return this;
      if (!other.availableForm_.isEmpty()) {
        if (availableForm_.isEmpty()) {
          availableForm_ = other.availableForm_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAvailableFormIsMutable();
          availableForm_.addAll(other.availableForm_);
        }
        onChanged();
      }
      if (other.getCandyCost() != 0) {
        setCandyCost(other.getCandyCost());
      }
      if (other.getStardustCost() != 0) {
        setStardustCost(other.getStardustCost());
      }
      if (other.itemCost_ != 0) {
        setItemCostValue(other.getItemCostValue());
      }
      if (questRequirementBuilder_ == null) {
        if (!other.questRequirement_.isEmpty()) {
          if (questRequirement_.isEmpty()) {
            questRequirement_ = other.questRequirement_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureQuestRequirementIsMutable();
            questRequirement_.addAll(other.questRequirement_);
          }
          onChanged();
        }
      } else {
        if (!other.questRequirement_.isEmpty()) {
          if (questRequirementBuilder_.isEmpty()) {
            questRequirementBuilder_.dispose();
            questRequirementBuilder_ = null;
            questRequirement_ = other.questRequirement_;
            bitField0_ = (bitField0_ & ~0x00000002);
            questRequirementBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQuestRequirementFieldBuilder() : null;
          } else {
            questRequirementBuilder_.addAllMessages(other.questRequirement_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.FormChangeProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.FormChangeProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> availableForm_ =
      java.util.Collections.emptyList();
    private void ensureAvailableFormIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        availableForm_ = new java.util.ArrayList<java.lang.Integer>(availableForm_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @return A list containing the availableForm.
     */
    public java.util.List<POGOProtos.Rpc.PokemonDisplayProto.Form> getAvailableFormList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, POGOProtos.Rpc.PokemonDisplayProto.Form>(availableForm_, availableForm_converter_);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @return The count of availableForm.
     */
    public int getAvailableFormCount() {
      return availableForm_.size();
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param index The index of the element to return.
     * @return The availableForm at the given index.
     */
    public POGOProtos.Rpc.PokemonDisplayProto.Form getAvailableForm(int index) {
      return availableForm_converter_.convert(availableForm_.get(index));
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param index The index to set the value at.
     * @param value The availableForm to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableForm(
        int index, POGOProtos.Rpc.PokemonDisplayProto.Form value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAvailableFormIsMutable();
      availableForm_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param value The availableForm to add.
     * @return This builder for chaining.
     */
    public Builder addAvailableForm(POGOProtos.Rpc.PokemonDisplayProto.Form value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAvailableFormIsMutable();
      availableForm_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param values The availableForm to add.
     * @return This builder for chaining.
     */
    public Builder addAllAvailableForm(
        java.lang.Iterable<? extends POGOProtos.Rpc.PokemonDisplayProto.Form> values) {
      ensureAvailableFormIsMutable();
      for (POGOProtos.Rpc.PokemonDisplayProto.Form value : values) {
        availableForm_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailableForm() {
      availableForm_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @return A list containing the enum numeric values on the wire for availableForm.
     */
    public java.util.List<java.lang.Integer>
    getAvailableFormValueList() {
      return java.util.Collections.unmodifiableList(availableForm_);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of availableForm at the given index.
     */
    public int getAvailableFormValue(int index) {
      return availableForm_.get(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of availableForm at the given index.
     * @return This builder for chaining.
     */
    public Builder setAvailableFormValue(
        int index, int value) {
      ensureAvailableFormIsMutable();
      availableForm_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param value The enum numeric value on the wire for availableForm to add.
     * @return This builder for chaining.
     */
    public Builder addAvailableFormValue(int value) {
      ensureAvailableFormIsMutable();
      availableForm_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.PokemonDisplayProto.Form available_form = 1;</code>
     * @param values The enum numeric values on the wire for availableForm to add.
     * @return This builder for chaining.
     */
    public Builder addAllAvailableFormValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureAvailableFormIsMutable();
      for (int value : values) {
        availableForm_.add(value);
      }
      onChanged();
      return this;
    }

    private int candyCost_ ;
    /**
     * <code>int32 candy_cost = 2;</code>
     * @return The candyCost.
     */
    @java.lang.Override
    public int getCandyCost() {
      return candyCost_;
    }
    /**
     * <code>int32 candy_cost = 2;</code>
     * @param value The candyCost to set.
     * @return This builder for chaining.
     */
    public Builder setCandyCost(int value) {
      
      candyCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candy_cost = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandyCost() {
      
      candyCost_ = 0;
      onChanged();
      return this;
    }

    private int stardustCost_ ;
    /**
     * <code>int32 stardust_cost = 3;</code>
     * @return The stardustCost.
     */
    @java.lang.Override
    public int getStardustCost() {
      return stardustCost_;
    }
    /**
     * <code>int32 stardust_cost = 3;</code>
     * @param value The stardustCost to set.
     * @return This builder for chaining.
     */
    public Builder setStardustCost(int value) {
      
      stardustCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stardust_cost = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStardustCost() {
      
      stardustCost_ = 0;
      onChanged();
      return this;
    }

    private int itemCost_ = 0;
    /**
     * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
     * @return The enum numeric value on the wire for itemCost.
     */
    @java.lang.Override public int getItemCostValue() {
      return itemCost_;
    }
    /**
     * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
     * @param value The enum numeric value on the wire for itemCost to set.
     * @return This builder for chaining.
     */
    public Builder setItemCostValue(int value) {
      
      itemCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
     * @return The itemCost.
     */
    @java.lang.Override
    public POGOProtos.Rpc.Item getItemCost() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.Item result = POGOProtos.Rpc.Item.valueOf(itemCost_);
      return result == null ? POGOProtos.Rpc.Item.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
     * @param value The itemCost to set.
     * @return This builder for chaining.
     */
    public Builder setItemCost(POGOProtos.Rpc.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      itemCost_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.Item item_cost = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemCost() {
      
      itemCost_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<POGOProtos.Rpc.EvolutionQuestInfoProto> questRequirement_ =
      java.util.Collections.emptyList();
    private void ensureQuestRequirementIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        questRequirement_ = new java.util.ArrayList<POGOProtos.Rpc.EvolutionQuestInfoProto>(questRequirement_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.EvolutionQuestInfoProto, POGOProtos.Rpc.EvolutionQuestInfoProto.Builder, POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder> questRequirementBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public java.util.List<POGOProtos.Rpc.EvolutionQuestInfoProto> getQuestRequirementList() {
      if (questRequirementBuilder_ == null) {
        return java.util.Collections.unmodifiableList(questRequirement_);
      } else {
        return questRequirementBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public int getQuestRequirementCount() {
      if (questRequirementBuilder_ == null) {
        return questRequirement_.size();
      } else {
        return questRequirementBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public POGOProtos.Rpc.EvolutionQuestInfoProto getQuestRequirement(int index) {
      if (questRequirementBuilder_ == null) {
        return questRequirement_.get(index);
      } else {
        return questRequirementBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder setQuestRequirement(
        int index, POGOProtos.Rpc.EvolutionQuestInfoProto value) {
      if (questRequirementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestRequirementIsMutable();
        questRequirement_.set(index, value);
        onChanged();
      } else {
        questRequirementBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder setQuestRequirement(
        int index, POGOProtos.Rpc.EvolutionQuestInfoProto.Builder builderForValue) {
      if (questRequirementBuilder_ == null) {
        ensureQuestRequirementIsMutable();
        questRequirement_.set(index, builderForValue.build());
        onChanged();
      } else {
        questRequirementBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder addQuestRequirement(POGOProtos.Rpc.EvolutionQuestInfoProto value) {
      if (questRequirementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestRequirementIsMutable();
        questRequirement_.add(value);
        onChanged();
      } else {
        questRequirementBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder addQuestRequirement(
        int index, POGOProtos.Rpc.EvolutionQuestInfoProto value) {
      if (questRequirementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQuestRequirementIsMutable();
        questRequirement_.add(index, value);
        onChanged();
      } else {
        questRequirementBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder addQuestRequirement(
        POGOProtos.Rpc.EvolutionQuestInfoProto.Builder builderForValue) {
      if (questRequirementBuilder_ == null) {
        ensureQuestRequirementIsMutable();
        questRequirement_.add(builderForValue.build());
        onChanged();
      } else {
        questRequirementBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder addQuestRequirement(
        int index, POGOProtos.Rpc.EvolutionQuestInfoProto.Builder builderForValue) {
      if (questRequirementBuilder_ == null) {
        ensureQuestRequirementIsMutable();
        questRequirement_.add(index, builderForValue.build());
        onChanged();
      } else {
        questRequirementBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder addAllQuestRequirement(
        java.lang.Iterable<? extends POGOProtos.Rpc.EvolutionQuestInfoProto> values) {
      if (questRequirementBuilder_ == null) {
        ensureQuestRequirementIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questRequirement_);
        onChanged();
      } else {
        questRequirementBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder clearQuestRequirement() {
      if (questRequirementBuilder_ == null) {
        questRequirement_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        questRequirementBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public Builder removeQuestRequirement(int index) {
      if (questRequirementBuilder_ == null) {
        ensureQuestRequirementIsMutable();
        questRequirement_.remove(index);
        onChanged();
      } else {
        questRequirementBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public POGOProtos.Rpc.EvolutionQuestInfoProto.Builder getQuestRequirementBuilder(
        int index) {
      return getQuestRequirementFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder getQuestRequirementOrBuilder(
        int index) {
      if (questRequirementBuilder_ == null) {
        return questRequirement_.get(index);  } else {
        return questRequirementBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder> 
         getQuestRequirementOrBuilderList() {
      if (questRequirementBuilder_ != null) {
        return questRequirementBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(questRequirement_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public POGOProtos.Rpc.EvolutionQuestInfoProto.Builder addQuestRequirementBuilder() {
      return getQuestRequirementFieldBuilder().addBuilder(
          POGOProtos.Rpc.EvolutionQuestInfoProto.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public POGOProtos.Rpc.EvolutionQuestInfoProto.Builder addQuestRequirementBuilder(
        int index) {
      return getQuestRequirementFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.EvolutionQuestInfoProto.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.EvolutionQuestInfoProto quest_requirement = 5;</code>
     */
    public java.util.List<POGOProtos.Rpc.EvolutionQuestInfoProto.Builder> 
         getQuestRequirementBuilderList() {
      return getQuestRequirementFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.EvolutionQuestInfoProto, POGOProtos.Rpc.EvolutionQuestInfoProto.Builder, POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder> 
        getQuestRequirementFieldBuilder() {
      if (questRequirementBuilder_ == null) {
        questRequirementBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.EvolutionQuestInfoProto, POGOProtos.Rpc.EvolutionQuestInfoProto.Builder, POGOProtos.Rpc.EvolutionQuestInfoProtoOrBuilder>(
                questRequirement_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        questRequirement_ = null;
      }
      return questRequirementBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.FormChangeProto)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.FormChangeProto)
  private static final POGOProtos.Rpc.FormChangeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.FormChangeProto();
  }

  public static POGOProtos.Rpc.FormChangeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FormChangeProto>
      PARSER = new com.google.protobuf.AbstractParser<FormChangeProto>() {
    @java.lang.Override
    public FormChangeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FormChangeProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FormChangeProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FormChangeProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.FormChangeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

