// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface GetAvailableSubmissionsProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.GetAvailableSubmissionsProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .POGOProtos.Rpc.PlayerSubmissionTypeProto submission_types = 1;</code>
   * @return A list containing the submissionTypes.
   */
  java.util.List<POGOProtos.Rpc.PlayerSubmissionTypeProto> getSubmissionTypesList();
  /**
   * <code>repeated .POGOProtos.Rpc.PlayerSubmissionTypeProto submission_types = 1;</code>
   * @return The count of submissionTypes.
   */
  int getSubmissionTypesCount();
  /**
   * <code>repeated .POGOProtos.Rpc.PlayerSubmissionTypeProto submission_types = 1;</code>
   * @param index The index of the element to return.
   * @return The submissionTypes at the given index.
   */
  POGOProtos.Rpc.PlayerSubmissionTypeProto getSubmissionTypes(int index);
  /**
   * <code>repeated .POGOProtos.Rpc.PlayerSubmissionTypeProto submission_types = 1;</code>
   * @return A list containing the enum numeric values on the wire for submissionTypes.
   */
  java.util.List<java.lang.Integer>
  getSubmissionTypesValueList();
  /**
   * <code>repeated .POGOProtos.Rpc.PlayerSubmissionTypeProto submission_types = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of submissionTypes at the given index.
   */
  int getSubmissionTypesValue(int index);
}
