// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface GetIncomingGameInvitesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.GetIncomingGameInvitesRequest)
    com.google.protobuf.MessageOrBuilder {
}
