// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse}
 */
public final class GetIncomingGameInvitesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.GetIncomingGameInvitesResponse)
    GetIncomingGameInvitesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetIncomingGameInvitesResponse.newBuilder() to construct.
  private GetIncomingGameInvitesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetIncomingGameInvitesResponse() {
    invites_ = java.util.Collections.emptyList();
    result_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetIncomingGameInvitesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetIncomingGameInvitesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              invites_ = new java.util.ArrayList<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite>();
              mutable_bitField0_ |= 0x00000001;
            }
            invites_.add(
                input.readMessage(POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.parser(), extensionRegistry));
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            result_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        invites_ = java.util.Collections.unmodifiableList(invites_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.GetIncomingGameInvitesResponse.class, POGOProtos.Rpc.GetIncomingGameInvitesResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>ERROR_UNKNOWN = 2;</code>
     */
    ERROR_UNKNOWN(2),
    /**
     * <code>ERROR_FEATURE_DISABLED = 3;</code>
     */
    ERROR_FEATURE_DISABLED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>ERROR_UNKNOWN = 2;</code>
     */
    public static final int ERROR_UNKNOWN_VALUE = 2;
    /**
     * <code>ERROR_FEATURE_DISABLED = 3;</code>
     */
    public static final int ERROR_FEATURE_DISABLED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Result forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return SUCCESS;
        case 2: return ERROR_UNKNOWN;
        case 3: return ERROR_FEATURE_DISABLED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Rpc.GetIncomingGameInvitesResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result)
  }

  public interface IncomingGameInviteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string app_key = 1;</code>
     * @return The appKey.
     */
    java.lang.String getAppKey();
    /**
     * <code>string app_key = 1;</code>
     * @return The bytes for appKey.
     */
    com.google.protobuf.ByteString
        getAppKeyBytes();

    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @return A list containing the friendProfileNames.
     */
    java.util.List<java.lang.String>
        getFriendProfileNamesList();
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @return The count of friendProfileNames.
     */
    int getFriendProfileNamesCount();
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @param index The index of the element to return.
     * @return The friendProfileNames at the given index.
     */
    java.lang.String getFriendProfileNames(int index);
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the friendProfileNames at the given index.
     */
    com.google.protobuf.ByteString
        getFriendProfileNamesBytes(int index);

    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
     * @return The status.
     */
    POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status getStatus();
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite}
   */
  public static final class IncomingGameInvite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)
      IncomingGameInviteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IncomingGameInvite.newBuilder() to construct.
    private IncomingGameInvite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IncomingGameInvite() {
      appKey_ = "";
      friendProfileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IncomingGameInvite();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IncomingGameInvite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appKey_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                friendProfileNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              friendProfileNames_.add(s);
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          friendProfileNames_ = friendProfileNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_IncomingGameInvite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_IncomingGameInvite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.class, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder.class);
    }

    /**
     * Protobuf enum {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSET = 0;</code>
       */
      UNSET(0),
      /**
       * <code>NEW = 1;</code>
       */
      NEW(1),
      /**
       * <code>SEEN = 2;</code>
       */
      SEEN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSET = 0;</code>
       */
      public static final int UNSET_VALUE = 0;
      /**
       * <code>NEW = 1;</code>
       */
      public static final int NEW_VALUE = 1;
      /**
       * <code>SEEN = 2;</code>
       */
      public static final int SEEN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return UNSET;
          case 1: return NEW;
          case 2: return SEEN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status)
    }

    public static final int APP_KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object appKey_;
    /**
     * <code>string app_key = 1;</code>
     * @return The appKey.
     */
    @java.lang.Override
    public java.lang.String getAppKey() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appKey_ = s;
        return s;
      }
    }
    /**
     * <code>string app_key = 1;</code>
     * @return The bytes for appKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_PROFILE_NAMES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList friendProfileNames_;
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @return A list containing the friendProfileNames.
     */
    public com.google.protobuf.ProtocolStringList
        getFriendProfileNamesList() {
      return friendProfileNames_;
    }
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @return The count of friendProfileNames.
     */
    public int getFriendProfileNamesCount() {
      return friendProfileNames_.size();
    }
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @param index The index of the element to return.
     * @return The friendProfileNames at the given index.
     */
    public java.lang.String getFriendProfileNames(int index) {
      return friendProfileNames_.get(index);
    }
    /**
     * <code>repeated string friend_profile_names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the friendProfileNames at the given index.
     */
    public com.google.protobuf.ByteString
        getFriendProfileNamesBytes(int index) {
      return friendProfileNames_.getByteString(index);
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
     * @return The status.
     */
    @java.lang.Override public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status getStatus() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status result = POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.valueOf(status_);
      return result == null ? POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appKey_);
      }
      for (int i = 0; i < friendProfileNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, friendProfileNames_.getRaw(i));
      }
      if (status_ != POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.UNSET.getNumber()) {
        output.writeEnum(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < friendProfileNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(friendProfileNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFriendProfileNamesList().size();
      }
      if (status_ != POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.UNSET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)) {
        return super.equals(obj);
      }
      POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite other = (POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite) obj;

      if (!getAppKey()
          .equals(other.getAppKey())) return false;
      if (!getFriendProfileNamesList()
          .equals(other.getFriendProfileNamesList())) return false;
      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APP_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppKey().hashCode();
      if (getFriendProfileNamesCount() > 0) {
        hash = (37 * hash) + FRIEND_PROFILE_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getFriendProfileNamesList().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_IncomingGameInvite_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_IncomingGameInvite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.class, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder.class);
      }

      // Construct using POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appKey_ = "";

        friendProfileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_IncomingGameInvite_descriptor;
      }

      @java.lang.Override
      public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite getDefaultInstanceForType() {
        return POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.getDefaultInstance();
      }

      @java.lang.Override
      public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite build() {
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite buildPartial() {
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite result = new POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite(this);
        int from_bitField0_ = bitField0_;
        result.appKey_ = appKey_;
        if (((bitField0_ & 0x00000001) != 0)) {
          friendProfileNames_ = friendProfileNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.friendProfileNames_ = friendProfileNames_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite) {
          return mergeFrom((POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite other) {
        if (other == POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.getDefaultInstance()) return this;
        if (!other.getAppKey().isEmpty()) {
          appKey_ = other.appKey_;
          onChanged();
        }
        if (!other.friendProfileNames_.isEmpty()) {
          if (friendProfileNames_.isEmpty()) {
            friendProfileNames_ = other.friendProfileNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFriendProfileNamesIsMutable();
            friendProfileNames_.addAll(other.friendProfileNames_);
          }
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appKey_ = "";
      /**
       * <code>string app_key = 1;</code>
       * @return The appKey.
       */
      public java.lang.String getAppKey() {
        java.lang.Object ref = appKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_key = 1;</code>
       * @return The bytes for appKey.
       */
      public com.google.protobuf.ByteString
          getAppKeyBytes() {
        java.lang.Object ref = appKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_key = 1;</code>
       * @param value The appKey to set.
       * @return This builder for chaining.
       */
      public Builder setAppKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppKey() {
        
        appKey_ = getDefaultInstance().getAppKey();
        onChanged();
        return this;
      }
      /**
       * <code>string app_key = 1;</code>
       * @param value The bytes for appKey to set.
       * @return This builder for chaining.
       */
      public Builder setAppKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appKey_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList friendProfileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFriendProfileNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          friendProfileNames_ = new com.google.protobuf.LazyStringArrayList(friendProfileNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @return A list containing the friendProfileNames.
       */
      public com.google.protobuf.ProtocolStringList
          getFriendProfileNamesList() {
        return friendProfileNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @return The count of friendProfileNames.
       */
      public int getFriendProfileNamesCount() {
        return friendProfileNames_.size();
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param index The index of the element to return.
       * @return The friendProfileNames at the given index.
       */
      public java.lang.String getFriendProfileNames(int index) {
        return friendProfileNames_.get(index);
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the friendProfileNames at the given index.
       */
      public com.google.protobuf.ByteString
          getFriendProfileNamesBytes(int index) {
        return friendProfileNames_.getByteString(index);
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param index The index to set the value at.
       * @param value The friendProfileNames to set.
       * @return This builder for chaining.
       */
      public Builder setFriendProfileNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendProfileNamesIsMutable();
        friendProfileNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param value The friendProfileNames to add.
       * @return This builder for chaining.
       */
      public Builder addFriendProfileNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendProfileNamesIsMutable();
        friendProfileNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param values The friendProfileNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllFriendProfileNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureFriendProfileNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, friendProfileNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFriendProfileNames() {
        friendProfileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friend_profile_names = 2;</code>
       * @param value The bytes of the friendProfileNames to add.
       * @return This builder for chaining.
       */
      public Builder addFriendProfileNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFriendProfileNamesIsMutable();
        friendProfileNames_.add(value);
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status getStatus() {
        @SuppressWarnings("deprecation")
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status result = POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.valueOf(status_);
        return result == null ? POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Status status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite)
    private static final POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite();
    }

    public static POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IncomingGameInvite>
        PARSER = new com.google.protobuf.AbstractParser<IncomingGameInvite>() {
      @java.lang.Override
      public IncomingGameInvite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IncomingGameInvite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IncomingGameInvite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IncomingGameInvite> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int INVITES_FIELD_NUMBER = 1;
  private java.util.List<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite> invites_;
  /**
   * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite> getInvitesList() {
    return invites_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder> 
      getInvitesOrBuilderList() {
    return invites_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
   */
  @java.lang.Override
  public int getInvitesCount() {
    return invites_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite getInvites(int index) {
    return invites_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder getInvitesOrBuilder(
      int index) {
    return invites_.get(index);
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private int result_;
  /**
   * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
   * @return The enum numeric value on the wire for result.
   */
  @java.lang.Override public int getResultValue() {
    return result_;
  }
  /**
   * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
   * @return The result.
   */
  @java.lang.Override public POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result getResult() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.valueOf(result_);
    return result == null ? POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < invites_.size(); i++) {
      output.writeMessage(1, invites_.get(i));
    }
    if (result_ != POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.UNSET.getNumber()) {
      output.writeEnum(2, result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < invites_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, invites_.get(i));
    }
    if (result_ != POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.GetIncomingGameInvitesResponse)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.GetIncomingGameInvitesResponse other = (POGOProtos.Rpc.GetIncomingGameInvitesResponse) obj;

    if (!getInvitesList()
        .equals(other.getInvitesList())) return false;
    if (result_ != other.result_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInvitesCount() > 0) {
      hash = (37 * hash) + INVITES_FIELD_NUMBER;
      hash = (53 * hash) + getInvitesList().hashCode();
    }
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + result_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.GetIncomingGameInvitesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.GetIncomingGameInvitesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.GetIncomingGameInvitesResponse)
      POGOProtos.Rpc.GetIncomingGameInvitesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.GetIncomingGameInvitesResponse.class, POGOProtos.Rpc.GetIncomingGameInvitesResponse.Builder.class);
    }

    // Construct using POGOProtos.Rpc.GetIncomingGameInvitesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInvitesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (invitesBuilder_ == null) {
        invites_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        invitesBuilder_.clear();
      }
      result_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_GetIncomingGameInvitesResponse_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse getDefaultInstanceForType() {
      return POGOProtos.Rpc.GetIncomingGameInvitesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse build() {
      POGOProtos.Rpc.GetIncomingGameInvitesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse buildPartial() {
      POGOProtos.Rpc.GetIncomingGameInvitesResponse result = new POGOProtos.Rpc.GetIncomingGameInvitesResponse(this);
      int from_bitField0_ = bitField0_;
      if (invitesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          invites_ = java.util.Collections.unmodifiableList(invites_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.invites_ = invites_;
      } else {
        result.invites_ = invitesBuilder_.build();
      }
      result.result_ = result_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.GetIncomingGameInvitesResponse) {
        return mergeFrom((POGOProtos.Rpc.GetIncomingGameInvitesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.GetIncomingGameInvitesResponse other) {
      if (other == POGOProtos.Rpc.GetIncomingGameInvitesResponse.getDefaultInstance()) return this;
      if (invitesBuilder_ == null) {
        if (!other.invites_.isEmpty()) {
          if (invites_.isEmpty()) {
            invites_ = other.invites_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInvitesIsMutable();
            invites_.addAll(other.invites_);
          }
          onChanged();
        }
      } else {
        if (!other.invites_.isEmpty()) {
          if (invitesBuilder_.isEmpty()) {
            invitesBuilder_.dispose();
            invitesBuilder_ = null;
            invites_ = other.invites_;
            bitField0_ = (bitField0_ & ~0x00000001);
            invitesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvitesFieldBuilder() : null;
          } else {
            invitesBuilder_.addAllMessages(other.invites_);
          }
        }
      }
      if (other.result_ != 0) {
        setResultValue(other.getResultValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.GetIncomingGameInvitesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.GetIncomingGameInvitesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite> invites_ =
      java.util.Collections.emptyList();
    private void ensureInvitesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        invites_ = new java.util.ArrayList<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite>(invites_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder> invitesBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite> getInvitesList() {
      if (invitesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invites_);
      } else {
        return invitesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public int getInvitesCount() {
      if (invitesBuilder_ == null) {
        return invites_.size();
      } else {
        return invitesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite getInvites(int index) {
      if (invitesBuilder_ == null) {
        return invites_.get(index);
      } else {
        return invitesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder setInvites(
        int index, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.set(index, value);
        onChanged();
      } else {
        invitesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder setInvites(
        int index, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.set(index, builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder addInvites(POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.add(value);
        onChanged();
      } else {
        invitesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder addInvites(
        int index, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.add(index, value);
        onChanged();
      } else {
        invitesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder addInvites(
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.add(builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder addInvites(
        int index, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.add(index, builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder addAllInvites(
        java.lang.Iterable<? extends POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite> values) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invites_);
        onChanged();
      } else {
        invitesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder clearInvites() {
      if (invitesBuilder_ == null) {
        invites_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        invitesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public Builder removeInvites(int index) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.remove(index);
        onChanged();
      } else {
        invitesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder getInvitesBuilder(
        int index) {
      return getInvitesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder getInvitesOrBuilder(
        int index) {
      if (invitesBuilder_ == null) {
        return invites_.get(index);  } else {
        return invitesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder> 
         getInvitesOrBuilderList() {
      if (invitesBuilder_ != null) {
        return invitesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invites_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder addInvitesBuilder() {
      return getInvitesFieldBuilder().addBuilder(
          POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder addInvitesBuilder(
        int index) {
      return getInvitesFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite invites = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder> 
         getInvitesBuilderList() {
      return getInvitesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder> 
        getInvitesFieldBuilder() {
      if (invitesBuilder_ == null) {
        invitesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInvite.Builder, POGOProtos.Rpc.GetIncomingGameInvitesResponse.IncomingGameInviteOrBuilder>(
                invites_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        invites_ = null;
      }
      return invitesBuilder_;
    }

    private int result_ = 0;
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
     * @param value The enum numeric value on the wire for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultValue(int value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
     * @return The result.
     */
    @java.lang.Override
    public POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result getResult() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.valueOf(result_);
      return result == null ? POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.GetIncomingGameInvitesResponse.Result result = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.GetIncomingGameInvitesResponse)
  private static final POGOProtos.Rpc.GetIncomingGameInvitesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.GetIncomingGameInvitesResponse();
  }

  public static POGOProtos.Rpc.GetIncomingGameInvitesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetIncomingGameInvitesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetIncomingGameInvitesResponse>() {
    @java.lang.Override
    public GetIncomingGameInvitesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetIncomingGameInvitesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetIncomingGameInvitesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetIncomingGameInvitesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.GetIncomingGameInvitesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

