// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface ImageGalleryTelemetryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.ImageGalleryTelemetry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.ImageGalleryTelemetry.ImageGalleryEventId image_gallery_telemetry_id = 1;</code>
   * @return The enum numeric value on the wire for imageGalleryTelemetryId.
   */
  int getImageGalleryTelemetryIdValue();
  /**
   * <code>.POGOProtos.Rpc.ImageGalleryTelemetry.ImageGalleryEventId image_gallery_telemetry_id = 1;</code>
   * @return The imageGalleryTelemetryId.
   */
  POGOProtos.Rpc.ImageGalleryTelemetry.ImageGalleryEventId getImageGalleryTelemetryId();
}
