// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.IncidentPrioritySettingsProto}
 */
public final class IncidentPrioritySettingsProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.IncidentPrioritySettingsProto)
    IncidentPrioritySettingsProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IncidentPrioritySettingsProto.newBuilder() to construct.
  private IncidentPrioritySettingsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IncidentPrioritySettingsProto() {
    incidentPriority_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IncidentPrioritySettingsProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IncidentPrioritySettingsProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              incidentPriority_ = new java.util.ArrayList<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority>();
              mutable_bitField0_ |= 0x00000001;
            }
            incidentPriority_.add(
                input.readMessage(POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        incidentPriority_ = java.util.Collections.unmodifiableList(incidentPriority_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.IncidentPrioritySettingsProto.class, POGOProtos.Rpc.IncidentPrioritySettingsProto.Builder.class);
  }

  public interface IncidentPriorityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 priority = 1;</code>
     * @return The priority.
     */
    int getPriority();

    /**
     * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
     * @return The enum numeric value on the wire for displayType.
     */
    int getDisplayTypeValue();
    /**
     * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
     * @return The displayType.
     */
    POGOProtos.Rpc.IncidentDisplayType getDisplayType();

    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return A list containing the oneOfBadgeTypes.
     */
    java.util.List<POGOProtos.Rpc.HoloBadgeType> getOneOfBadgeTypesList();
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return The count of oneOfBadgeTypes.
     */
    int getOneOfBadgeTypesCount();
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @param index The index of the element to return.
     * @return The oneOfBadgeTypes at the given index.
     */
    POGOProtos.Rpc.HoloBadgeType getOneOfBadgeTypes(int index);
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return A list containing the enum numeric values on the wire for oneOfBadgeTypes.
     */
    java.util.List<java.lang.Integer>
    getOneOfBadgeTypesValueList();
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of oneOfBadgeTypes at the given index.
     */
    int getOneOfBadgeTypesValue(int index);
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority}
   */
  public static final class IncidentPriority extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)
      IncidentPriorityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IncidentPriority.newBuilder() to construct.
    private IncidentPriority(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IncidentPriority() {
      displayType_ = 0;
      oneOfBadgeTypes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IncidentPriority();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IncidentPriority(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              priority_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              displayType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                oneOfBadgeTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              oneOfBadgeTypes_.add(rawValue);
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  oneOfBadgeTypes_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                oneOfBadgeTypes_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          oneOfBadgeTypes_ = java.util.Collections.unmodifiableList(oneOfBadgeTypes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_IncidentPriority_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_IncidentPriority_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.class, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder.class);
    }

    public static final int PRIORITY_FIELD_NUMBER = 1;
    private int priority_;
    /**
     * <code>int32 priority = 1;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }

    public static final int DISPLAY_TYPE_FIELD_NUMBER = 2;
    private int displayType_;
    /**
     * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
     * @return The enum numeric value on the wire for displayType.
     */
    @java.lang.Override public int getDisplayTypeValue() {
      return displayType_;
    }
    /**
     * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
     * @return The displayType.
     */
    @java.lang.Override public POGOProtos.Rpc.IncidentDisplayType getDisplayType() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.IncidentDisplayType result = POGOProtos.Rpc.IncidentDisplayType.valueOf(displayType_);
      return result == null ? POGOProtos.Rpc.IncidentDisplayType.UNRECOGNIZED : result;
    }

    public static final int ONE_OF_BADGE_TYPES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> oneOfBadgeTypes_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, POGOProtos.Rpc.HoloBadgeType> oneOfBadgeTypes_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, POGOProtos.Rpc.HoloBadgeType>() {
              public POGOProtos.Rpc.HoloBadgeType convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                POGOProtos.Rpc.HoloBadgeType result = POGOProtos.Rpc.HoloBadgeType.valueOf(from);
                return result == null ? POGOProtos.Rpc.HoloBadgeType.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return A list containing the oneOfBadgeTypes.
     */
    @java.lang.Override
    public java.util.List<POGOProtos.Rpc.HoloBadgeType> getOneOfBadgeTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, POGOProtos.Rpc.HoloBadgeType>(oneOfBadgeTypes_, oneOfBadgeTypes_converter_);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return The count of oneOfBadgeTypes.
     */
    @java.lang.Override
    public int getOneOfBadgeTypesCount() {
      return oneOfBadgeTypes_.size();
    }
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @param index The index of the element to return.
     * @return The oneOfBadgeTypes at the given index.
     */
    @java.lang.Override
    public POGOProtos.Rpc.HoloBadgeType getOneOfBadgeTypes(int index) {
      return oneOfBadgeTypes_converter_.convert(oneOfBadgeTypes_.get(index));
    }
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @return A list containing the enum numeric values on the wire for oneOfBadgeTypes.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getOneOfBadgeTypesValueList() {
      return oneOfBadgeTypes_;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of oneOfBadgeTypes at the given index.
     */
    @java.lang.Override
    public int getOneOfBadgeTypesValue(int index) {
      return oneOfBadgeTypes_.get(index);
    }
    private int oneOfBadgeTypesMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (priority_ != 0) {
        output.writeInt32(1, priority_);
      }
      if (displayType_ != POGOProtos.Rpc.IncidentDisplayType.INCIDENT_DISPLAY_TYPE_NONE.getNumber()) {
        output.writeEnum(2, displayType_);
      }
      if (getOneOfBadgeTypesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(oneOfBadgeTypesMemoizedSerializedSize);
      }
      for (int i = 0; i < oneOfBadgeTypes_.size(); i++) {
        output.writeEnumNoTag(oneOfBadgeTypes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (priority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, priority_);
      }
      if (displayType_ != POGOProtos.Rpc.IncidentDisplayType.INCIDENT_DISPLAY_TYPE_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, displayType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < oneOfBadgeTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(oneOfBadgeTypes_.get(i));
        }
        size += dataSize;
        if (!getOneOfBadgeTypesList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }oneOfBadgeTypesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)) {
        return super.equals(obj);
      }
      POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority other = (POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority) obj;

      if (getPriority()
          != other.getPriority()) return false;
      if (displayType_ != other.displayType_) return false;
      if (!oneOfBadgeTypes_.equals(other.oneOfBadgeTypes_)) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
      hash = (37 * hash) + DISPLAY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + displayType_;
      if (getOneOfBadgeTypesCount() > 0) {
        hash = (37 * hash) + ONE_OF_BADGE_TYPES_FIELD_NUMBER;
        hash = (53 * hash) + oneOfBadgeTypes_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_IncidentPriority_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_IncidentPriority_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.class, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder.class);
      }

      // Construct using POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        priority_ = 0;

        displayType_ = 0;

        oneOfBadgeTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_IncidentPriority_descriptor;
      }

      @java.lang.Override
      public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getDefaultInstanceForType() {
        return POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.getDefaultInstance();
      }

      @java.lang.Override
      public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority build() {
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority buildPartial() {
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority result = new POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority(this);
        int from_bitField0_ = bitField0_;
        result.priority_ = priority_;
        result.displayType_ = displayType_;
        if (((bitField0_ & 0x00000001) != 0)) {
          oneOfBadgeTypes_ = java.util.Collections.unmodifiableList(oneOfBadgeTypes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.oneOfBadgeTypes_ = oneOfBadgeTypes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority) {
          return mergeFrom((POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority other) {
        if (other == POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.getDefaultInstance()) return this;
        if (other.getPriority() != 0) {
          setPriority(other.getPriority());
        }
        if (other.displayType_ != 0) {
          setDisplayTypeValue(other.getDisplayTypeValue());
        }
        if (!other.oneOfBadgeTypes_.isEmpty()) {
          if (oneOfBadgeTypes_.isEmpty()) {
            oneOfBadgeTypes_ = other.oneOfBadgeTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOneOfBadgeTypesIsMutable();
            oneOfBadgeTypes_.addAll(other.oneOfBadgeTypes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int priority_ ;
      /**
       * <code>int32 priority = 1;</code>
       * @return The priority.
       */
      @java.lang.Override
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>int32 priority = 1;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priority = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        
        priority_ = 0;
        onChanged();
        return this;
      }

      private int displayType_ = 0;
      /**
       * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
       * @return The enum numeric value on the wire for displayType.
       */
      @java.lang.Override public int getDisplayTypeValue() {
        return displayType_;
      }
      /**
       * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
       * @param value The enum numeric value on the wire for displayType to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayTypeValue(int value) {
        
        displayType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
       * @return The displayType.
       */
      @java.lang.Override
      public POGOProtos.Rpc.IncidentDisplayType getDisplayType() {
        @SuppressWarnings("deprecation")
        POGOProtos.Rpc.IncidentDisplayType result = POGOProtos.Rpc.IncidentDisplayType.valueOf(displayType_);
        return result == null ? POGOProtos.Rpc.IncidentDisplayType.UNRECOGNIZED : result;
      }
      /**
       * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
       * @param value The displayType to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayType(POGOProtos.Rpc.IncidentDisplayType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        displayType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.POGOProtos.Rpc.IncidentDisplayType display_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisplayType() {
        
        displayType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> oneOfBadgeTypes_ =
        java.util.Collections.emptyList();
      private void ensureOneOfBadgeTypesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          oneOfBadgeTypes_ = new java.util.ArrayList<java.lang.Integer>(oneOfBadgeTypes_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @return A list containing the oneOfBadgeTypes.
       */
      public java.util.List<POGOProtos.Rpc.HoloBadgeType> getOneOfBadgeTypesList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, POGOProtos.Rpc.HoloBadgeType>(oneOfBadgeTypes_, oneOfBadgeTypes_converter_);
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @return The count of oneOfBadgeTypes.
       */
      public int getOneOfBadgeTypesCount() {
        return oneOfBadgeTypes_.size();
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param index The index of the element to return.
       * @return The oneOfBadgeTypes at the given index.
       */
      public POGOProtos.Rpc.HoloBadgeType getOneOfBadgeTypes(int index) {
        return oneOfBadgeTypes_converter_.convert(oneOfBadgeTypes_.get(index));
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param index The index to set the value at.
       * @param value The oneOfBadgeTypes to set.
       * @return This builder for chaining.
       */
      public Builder setOneOfBadgeTypes(
          int index, POGOProtos.Rpc.HoloBadgeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOneOfBadgeTypesIsMutable();
        oneOfBadgeTypes_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param value The oneOfBadgeTypes to add.
       * @return This builder for chaining.
       */
      public Builder addOneOfBadgeTypes(POGOProtos.Rpc.HoloBadgeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOneOfBadgeTypesIsMutable();
        oneOfBadgeTypes_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param values The oneOfBadgeTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllOneOfBadgeTypes(
          java.lang.Iterable<? extends POGOProtos.Rpc.HoloBadgeType> values) {
        ensureOneOfBadgeTypesIsMutable();
        for (POGOProtos.Rpc.HoloBadgeType value : values) {
          oneOfBadgeTypes_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOneOfBadgeTypes() {
        oneOfBadgeTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @return A list containing the enum numeric values on the wire for oneOfBadgeTypes.
       */
      public java.util.List<java.lang.Integer>
      getOneOfBadgeTypesValueList() {
        return java.util.Collections.unmodifiableList(oneOfBadgeTypes_);
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of oneOfBadgeTypes at the given index.
       */
      public int getOneOfBadgeTypesValue(int index) {
        return oneOfBadgeTypes_.get(index);
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of oneOfBadgeTypes at the given index.
       * @return This builder for chaining.
       */
      public Builder setOneOfBadgeTypesValue(
          int index, int value) {
        ensureOneOfBadgeTypesIsMutable();
        oneOfBadgeTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param value The enum numeric value on the wire for oneOfBadgeTypes to add.
       * @return This builder for chaining.
       */
      public Builder addOneOfBadgeTypesValue(int value) {
        ensureOneOfBadgeTypesIsMutable();
        oneOfBadgeTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .POGOProtos.Rpc.HoloBadgeType one_of_badge_types = 3;</code>
       * @param values The enum numeric values on the wire for oneOfBadgeTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllOneOfBadgeTypesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureOneOfBadgeTypesIsMutable();
        for (int value : values) {
          oneOfBadgeTypes_.add(value);
        }
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority)
    private static final POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority();
    }

    public static POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IncidentPriority>
        PARSER = new com.google.protobuf.AbstractParser<IncidentPriority>() {
      @java.lang.Override
      public IncidentPriority parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IncidentPriority(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IncidentPriority> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IncidentPriority> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int INCIDENT_PRIORITY_FIELD_NUMBER = 1;
  private java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> incidentPriority_;
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  @java.lang.Override
  public java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> getIncidentPriorityList() {
    return incidentPriority_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder> 
      getIncidentPriorityOrBuilderList() {
    return incidentPriority_;
  }
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  @java.lang.Override
  public int getIncidentPriorityCount() {
    return incidentPriority_.size();
  }
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getIncidentPriority(int index) {
    return incidentPriority_.get(index);
  }
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder getIncidentPriorityOrBuilder(
      int index) {
    return incidentPriority_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < incidentPriority_.size(); i++) {
      output.writeMessage(1, incidentPriority_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < incidentPriority_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, incidentPriority_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.IncidentPrioritySettingsProto)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.IncidentPrioritySettingsProto other = (POGOProtos.Rpc.IncidentPrioritySettingsProto) obj;

    if (!getIncidentPriorityList()
        .equals(other.getIncidentPriorityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIncidentPriorityCount() > 0) {
      hash = (37 * hash) + INCIDENT_PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getIncidentPriorityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.IncidentPrioritySettingsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.IncidentPrioritySettingsProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.IncidentPrioritySettingsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.IncidentPrioritySettingsProto)
      POGOProtos.Rpc.IncidentPrioritySettingsProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.IncidentPrioritySettingsProto.class, POGOProtos.Rpc.IncidentPrioritySettingsProto.Builder.class);
    }

    // Construct using POGOProtos.Rpc.IncidentPrioritySettingsProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIncidentPriorityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (incidentPriorityBuilder_ == null) {
        incidentPriority_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        incidentPriorityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_IncidentPrioritySettingsProto_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncidentPrioritySettingsProto getDefaultInstanceForType() {
      return POGOProtos.Rpc.IncidentPrioritySettingsProto.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncidentPrioritySettingsProto build() {
      POGOProtos.Rpc.IncidentPrioritySettingsProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.IncidentPrioritySettingsProto buildPartial() {
      POGOProtos.Rpc.IncidentPrioritySettingsProto result = new POGOProtos.Rpc.IncidentPrioritySettingsProto(this);
      int from_bitField0_ = bitField0_;
      if (incidentPriorityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          incidentPriority_ = java.util.Collections.unmodifiableList(incidentPriority_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.incidentPriority_ = incidentPriority_;
      } else {
        result.incidentPriority_ = incidentPriorityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.IncidentPrioritySettingsProto) {
        return mergeFrom((POGOProtos.Rpc.IncidentPrioritySettingsProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.IncidentPrioritySettingsProto other) {
      if (other == POGOProtos.Rpc.IncidentPrioritySettingsProto.getDefaultInstance()) return this;
      if (incidentPriorityBuilder_ == null) {
        if (!other.incidentPriority_.isEmpty()) {
          if (incidentPriority_.isEmpty()) {
            incidentPriority_ = other.incidentPriority_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIncidentPriorityIsMutable();
            incidentPriority_.addAll(other.incidentPriority_);
          }
          onChanged();
        }
      } else {
        if (!other.incidentPriority_.isEmpty()) {
          if (incidentPriorityBuilder_.isEmpty()) {
            incidentPriorityBuilder_.dispose();
            incidentPriorityBuilder_ = null;
            incidentPriority_ = other.incidentPriority_;
            bitField0_ = (bitField0_ & ~0x00000001);
            incidentPriorityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIncidentPriorityFieldBuilder() : null;
          } else {
            incidentPriorityBuilder_.addAllMessages(other.incidentPriority_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.IncidentPrioritySettingsProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.IncidentPrioritySettingsProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> incidentPriority_ =
      java.util.Collections.emptyList();
    private void ensureIncidentPriorityIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        incidentPriority_ = new java.util.ArrayList<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority>(incidentPriority_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder> incidentPriorityBuilder_;

    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> getIncidentPriorityList() {
      if (incidentPriorityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(incidentPriority_);
      } else {
        return incidentPriorityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public int getIncidentPriorityCount() {
      if (incidentPriorityBuilder_ == null) {
        return incidentPriority_.size();
      } else {
        return incidentPriorityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getIncidentPriority(int index) {
      if (incidentPriorityBuilder_ == null) {
        return incidentPriority_.get(index);
      } else {
        return incidentPriorityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder setIncidentPriority(
        int index, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority value) {
      if (incidentPriorityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentPriorityIsMutable();
        incidentPriority_.set(index, value);
        onChanged();
      } else {
        incidentPriorityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder setIncidentPriority(
        int index, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder builderForValue) {
      if (incidentPriorityBuilder_ == null) {
        ensureIncidentPriorityIsMutable();
        incidentPriority_.set(index, builderForValue.build());
        onChanged();
      } else {
        incidentPriorityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder addIncidentPriority(POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority value) {
      if (incidentPriorityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentPriorityIsMutable();
        incidentPriority_.add(value);
        onChanged();
      } else {
        incidentPriorityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder addIncidentPriority(
        int index, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority value) {
      if (incidentPriorityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentPriorityIsMutable();
        incidentPriority_.add(index, value);
        onChanged();
      } else {
        incidentPriorityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder addIncidentPriority(
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder builderForValue) {
      if (incidentPriorityBuilder_ == null) {
        ensureIncidentPriorityIsMutable();
        incidentPriority_.add(builderForValue.build());
        onChanged();
      } else {
        incidentPriorityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder addIncidentPriority(
        int index, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder builderForValue) {
      if (incidentPriorityBuilder_ == null) {
        ensureIncidentPriorityIsMutable();
        incidentPriority_.add(index, builderForValue.build());
        onChanged();
      } else {
        incidentPriorityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder addAllIncidentPriority(
        java.lang.Iterable<? extends POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> values) {
      if (incidentPriorityBuilder_ == null) {
        ensureIncidentPriorityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, incidentPriority_);
        onChanged();
      } else {
        incidentPriorityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder clearIncidentPriority() {
      if (incidentPriorityBuilder_ == null) {
        incidentPriority_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        incidentPriorityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public Builder removeIncidentPriority(int index) {
      if (incidentPriorityBuilder_ == null) {
        ensureIncidentPriorityIsMutable();
        incidentPriority_.remove(index);
        onChanged();
      } else {
        incidentPriorityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder getIncidentPriorityBuilder(
        int index) {
      return getIncidentPriorityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder getIncidentPriorityOrBuilder(
        int index) {
      if (incidentPriorityBuilder_ == null) {
        return incidentPriority_.get(index);  } else {
        return incidentPriorityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public java.util.List<? extends POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder> 
         getIncidentPriorityOrBuilderList() {
      if (incidentPriorityBuilder_ != null) {
        return incidentPriorityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(incidentPriority_);
      }
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder addIncidentPriorityBuilder() {
      return getIncidentPriorityFieldBuilder().addBuilder(
          POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder addIncidentPriorityBuilder(
        int index) {
      return getIncidentPriorityFieldBuilder().addBuilder(
          index, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.getDefaultInstance());
    }
    /**
     * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
     */
    public java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder> 
         getIncidentPriorityBuilderList() {
      return getIncidentPriorityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder> 
        getIncidentPriorityFieldBuilder() {
      if (incidentPriorityBuilder_ == null) {
        incidentPriorityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority.Builder, POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder>(
                incidentPriority_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        incidentPriority_ = null;
      }
      return incidentPriorityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.IncidentPrioritySettingsProto)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.IncidentPrioritySettingsProto)
  private static final POGOProtos.Rpc.IncidentPrioritySettingsProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.IncidentPrioritySettingsProto();
  }

  public static POGOProtos.Rpc.IncidentPrioritySettingsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IncidentPrioritySettingsProto>
      PARSER = new com.google.protobuf.AbstractParser<IncidentPrioritySettingsProto>() {
    @java.lang.Override
    public IncidentPrioritySettingsProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IncidentPrioritySettingsProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IncidentPrioritySettingsProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IncidentPrioritySettingsProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.IncidentPrioritySettingsProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

