// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface IncidentPrioritySettingsProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.IncidentPrioritySettingsProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  java.util.List<POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority> 
      getIncidentPriorityList();
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority getIncidentPriority(int index);
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  int getIncidentPriorityCount();
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  java.util.List<? extends POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder> 
      getIncidentPriorityOrBuilderList();
  /**
   * <code>repeated .POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriority incident_priority = 1;</code>
   */
  POGOProtos.Rpc.IncidentPrioritySettingsProto.IncidentPriorityOrBuilder getIncidentPriorityOrBuilder(
      int index);
}
