// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface InviteGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.InviteGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.InviteGameResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.POGOProtos.Rpc.InviteGameResponse.Status status = 1;</code>
   * @return The status.
   */
  POGOProtos.Rpc.InviteGameResponse.Status getStatus();
}
