// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface InviteGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.InviteGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string friend_id = 1;</code>
   * @return The friendId.
   */
  java.lang.String getFriendId();
  /**
   * <code>string friend_id = 1;</code>
   * @return The bytes for friendId.
   */
  com.google.protobuf.ByteString
      getFriendIdBytes();

  /**
   * <code>string app_key = 2;</code>
   * @return The appKey.
   */
  java.lang.String getAppKey();
  /**
   * <code>string app_key = 2;</code>
   * @return The bytes for appKey.
   */
  com.google.protobuf.ByteString
      getAppKeyBytes();
}
