// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface ListFriendsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.ListFriendsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.SocialClientFeatures.CrossGameSocialClientSettingsProto.FeatureType feature = 1;</code>
   * @return The enum numeric value on the wire for feature.
   */
  int getFeatureValue();
  /**
   * <code>.POGOProtos.Rpc.SocialClientFeatures.CrossGameSocialClientSettingsProto.FeatureType feature = 1;</code>
   * @return The feature.
   */
  POGOProtos.Rpc.SocialClientFeatures.CrossGameSocialClientSettingsProto.FeatureType getFeature();
}
