// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry}
 */
public final class PlayerShownLevelUpShareScreenTelemetry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)
    PlayerShownLevelUpShareScreenTelemetryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerShownLevelUpShareScreenTelemetry.newBuilder() to construct.
  private PlayerShownLevelUpShareScreenTelemetry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerShownLevelUpShareScreenTelemetry() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerShownLevelUpShareScreenTelemetry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PlayerShownLevelUpShareScreenTelemetry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            playerViewedPhoto_ = input.readBool();
            break;
          }
          case 16: {

            playerSharedPhoto_ = input.readBool();
            break;
          }
          case 24: {

            playerLevel_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_PlayerShownLevelUpShareScreenTelemetry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_PlayerShownLevelUpShareScreenTelemetry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.class, POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.Builder.class);
  }

  public static final int PLAYER_VIEWED_PHOTO_FIELD_NUMBER = 1;
  private boolean playerViewedPhoto_;
  /**
   * <code>bool player_viewed_photo = 1;</code>
   * @return The playerViewedPhoto.
   */
  @java.lang.Override
  public boolean getPlayerViewedPhoto() {
    return playerViewedPhoto_;
  }

  public static final int PLAYER_SHARED_PHOTO_FIELD_NUMBER = 2;
  private boolean playerSharedPhoto_;
  /**
   * <code>bool player_shared_photo = 2;</code>
   * @return The playerSharedPhoto.
   */
  @java.lang.Override
  public boolean getPlayerSharedPhoto() {
    return playerSharedPhoto_;
  }

  public static final int PLAYER_LEVEL_FIELD_NUMBER = 3;
  private int playerLevel_;
  /**
   * <code>int32 player_level = 3;</code>
   * @return The playerLevel.
   */
  @java.lang.Override
  public int getPlayerLevel() {
    return playerLevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playerViewedPhoto_ != false) {
      output.writeBool(1, playerViewedPhoto_);
    }
    if (playerSharedPhoto_ != false) {
      output.writeBool(2, playerSharedPhoto_);
    }
    if (playerLevel_ != 0) {
      output.writeInt32(3, playerLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playerViewedPhoto_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, playerViewedPhoto_);
    }
    if (playerSharedPhoto_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, playerSharedPhoto_);
    }
    if (playerLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, playerLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry other = (POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry) obj;

    if (getPlayerViewedPhoto()
        != other.getPlayerViewedPhoto()) return false;
    if (getPlayerSharedPhoto()
        != other.getPlayerSharedPhoto()) return false;
    if (getPlayerLevel()
        != other.getPlayerLevel()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYER_VIEWED_PHOTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPlayerViewedPhoto());
    hash = (37 * hash) + PLAYER_SHARED_PHOTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPlayerSharedPhoto());
    hash = (37 * hash) + PLAYER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerLevel();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)
      POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_PlayerShownLevelUpShareScreenTelemetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_PlayerShownLevelUpShareScreenTelemetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.class, POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.Builder.class);
    }

    // Construct using POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      playerViewedPhoto_ = false;

      playerSharedPhoto_ = false;

      playerLevel_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_PlayerShownLevelUpShareScreenTelemetry_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry getDefaultInstanceForType() {
      return POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry build() {
      POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry buildPartial() {
      POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry result = new POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry(this);
      result.playerViewedPhoto_ = playerViewedPhoto_;
      result.playerSharedPhoto_ = playerSharedPhoto_;
      result.playerLevel_ = playerLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry) {
        return mergeFrom((POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry other) {
      if (other == POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry.getDefaultInstance()) return this;
      if (other.getPlayerViewedPhoto() != false) {
        setPlayerViewedPhoto(other.getPlayerViewedPhoto());
      }
      if (other.getPlayerSharedPhoto() != false) {
        setPlayerSharedPhoto(other.getPlayerSharedPhoto());
      }
      if (other.getPlayerLevel() != 0) {
        setPlayerLevel(other.getPlayerLevel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean playerViewedPhoto_ ;
    /**
     * <code>bool player_viewed_photo = 1;</code>
     * @return The playerViewedPhoto.
     */
    @java.lang.Override
    public boolean getPlayerViewedPhoto() {
      return playerViewedPhoto_;
    }
    /**
     * <code>bool player_viewed_photo = 1;</code>
     * @param value The playerViewedPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerViewedPhoto(boolean value) {
      
      playerViewedPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool player_viewed_photo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerViewedPhoto() {
      
      playerViewedPhoto_ = false;
      onChanged();
      return this;
    }

    private boolean playerSharedPhoto_ ;
    /**
     * <code>bool player_shared_photo = 2;</code>
     * @return The playerSharedPhoto.
     */
    @java.lang.Override
    public boolean getPlayerSharedPhoto() {
      return playerSharedPhoto_;
    }
    /**
     * <code>bool player_shared_photo = 2;</code>
     * @param value The playerSharedPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerSharedPhoto(boolean value) {
      
      playerSharedPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool player_shared_photo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerSharedPhoto() {
      
      playerSharedPhoto_ = false;
      onChanged();
      return this;
    }

    private int playerLevel_ ;
    /**
     * <code>int32 player_level = 3;</code>
     * @return The playerLevel.
     */
    @java.lang.Override
    public int getPlayerLevel() {
      return playerLevel_;
    }
    /**
     * <code>int32 player_level = 3;</code>
     * @param value The playerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerLevel(int value) {
      
      playerLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 player_level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerLevel() {
      
      playerLevel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry)
  private static final POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry();
  }

  public static POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerShownLevelUpShareScreenTelemetry>
      PARSER = new com.google.protobuf.AbstractParser<PlayerShownLevelUpShareScreenTelemetry>() {
    @java.lang.Override
    public PlayerShownLevelUpShareScreenTelemetry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PlayerShownLevelUpShareScreenTelemetry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlayerShownLevelUpShareScreenTelemetry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerShownLevelUpShareScreenTelemetry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.PlayerShownLevelUpShareScreenTelemetry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

