// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface TransferPokemonToPokemonHomeOutProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.TransferPokemonToPokemonHomeOutProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.TransferPokemonToPokemonHomeOutProto.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.POGOProtos.Rpc.TransferPokemonToPokemonHomeOutProto.Status status = 1;</code>
   * @return The status.
   */
  POGOProtos.Rpc.TransferPokemonToPokemonHomeOutProto.Status getStatus();

  /**
   * <code>int32 candy_awarded = 2;</code>
   * @return The candyAwarded.
   */
  int getCandyAwarded();

  /**
   * <code>int32 xl_candy_awarded = 3;</code>
   * @return The xlCandyAwarded.
   */
  int getXlCandyAwarded();

  /**
   * <code>map&lt;int32, int32&gt; xl_candy_awarded_per_id = 4;</code>
   */
  int getXlCandyAwardedPerIdCount();
  /**
   * <code>map&lt;int32, int32&gt; xl_candy_awarded_per_id = 4;</code>
   */
  boolean containsXlCandyAwardedPerId(
      int key);
  /**
   * Use {@link #getXlCandyAwardedPerIdMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getXlCandyAwardedPerId();
  /**
   * <code>map&lt;int32, int32&gt; xl_candy_awarded_per_id = 4;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getXlCandyAwardedPerIdMap();
  /**
   * <code>map&lt;int32, int32&gt; xl_candy_awarded_per_id = 4;</code>
   */

  int getXlCandyAwardedPerIdOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; xl_candy_awarded_per_id = 4;</code>
   */

  int getXlCandyAwardedPerIdOrThrow(
      int key);
}
