// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface UpdateIncomingGameInviteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.UpdateIncomingGameInviteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteResponse.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteResponse.Result result = 1;</code>
   * @return The result.
   */
  POGOProtos.Rpc.UpdateIncomingGameInviteResponse.Result getResult();
}
