// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.UpdateFriendshipRequest}
 */
public final class UpdateFriendshipRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.UpdateFriendshipRequest)
    UpdateFriendshipRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateFriendshipRequest.newBuilder() to construct.
  private UpdateFriendshipRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateFriendshipRequest() {
    friendId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateFriendshipRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateFriendshipRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            friendId_ = s;
            break;
          }
          case 18: {
            POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder subBuilder = null;
            if (friendProfile_ != null) {
              subBuilder = friendProfile_.toBuilder();
            }
            friendProfile_ = input.readMessage(POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(friendProfile_);
              friendProfile_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.UpdateFriendshipRequest.class, POGOProtos.Rpc.UpdateFriendshipRequest.Builder.class);
  }

  public interface FriendProfileProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nickname = 1;</code>
     * @return The nickname.
     */
    java.lang.String getNickname();
    /**
     * <code>string nickname = 1;</code>
     * @return The bytes for nickname.
     */
    com.google.protobuf.ByteString
        getNicknameBytes();
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto}
   */
  public static final class FriendProfileProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)
      FriendProfileProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FriendProfileProto.newBuilder() to construct.
    private FriendProfileProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendProfileProto() {
      nickname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FriendProfileProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FriendProfileProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_FriendProfileProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_FriendProfileProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.class, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder.class);
    }

    public static final int NICKNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nickname_;
    /**
     * <code>string nickname = 1;</code>
     * @return The nickname.
     */
    @java.lang.Override
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <code>string nickname = 1;</code>
     * @return The bytes for nickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nickname_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nickname_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)) {
        return super.equals(obj);
      }
      POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto other = (POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto) obj;

      if (!getNickname()
          .equals(other.getNickname())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_FriendProfileProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_FriendProfileProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.class, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder.class);
      }

      // Construct using POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nickname_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_FriendProfileProto_descriptor;
      }

      @java.lang.Override
      public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getDefaultInstanceForType() {
        return POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.getDefaultInstance();
      }

      @java.lang.Override
      public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto build() {
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto buildPartial() {
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto result = new POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto(this);
        result.nickname_ = nickname_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto) {
          return mergeFrom((POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto other) {
        if (other == POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.getDefaultInstance()) return this;
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>string nickname = 1;</code>
       * @return The nickname.
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickname = 1;</code>
       * @return The bytes for nickname.
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickname = 1;</code>
       * @param value The nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 1;</code>
       * @param value The bytes for nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto)
    private static final POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto();
    }

    public static POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FriendProfileProto>
        PARSER = new com.google.protobuf.AbstractParser<FriendProfileProto>() {
      @java.lang.Override
      public FriendProfileProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FriendProfileProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendProfileProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FriendProfileProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int FRIEND_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object friendId_;
  /**
   * <code>string friend_id = 1;</code>
   * @return The friendId.
   */
  @java.lang.Override
  public java.lang.String getFriendId() {
    java.lang.Object ref = friendId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      friendId_ = s;
      return s;
    }
  }
  /**
   * <code>string friend_id = 1;</code>
   * @return The bytes for friendId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFriendIdBytes() {
    java.lang.Object ref = friendId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      friendId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRIEND_PROFILE_FIELD_NUMBER = 2;
  private POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friendProfile_;
  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   * @return Whether the friendProfile field is set.
   */
  @java.lang.Override
  public boolean hasFriendProfile() {
    return friendProfile_ != null;
  }
  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   * @return The friendProfile.
   */
  @java.lang.Override
  public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getFriendProfile() {
    return friendProfile_ == null ? POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.getDefaultInstance() : friendProfile_;
  }
  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   */
  @java.lang.Override
  public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder getFriendProfileOrBuilder() {
    return getFriendProfile();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFriendIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, friendId_);
    }
    if (friendProfile_ != null) {
      output.writeMessage(2, getFriendProfile());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFriendIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, friendId_);
    }
    if (friendProfile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFriendProfile());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.UpdateFriendshipRequest)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.UpdateFriendshipRequest other = (POGOProtos.Rpc.UpdateFriendshipRequest) obj;

    if (!getFriendId()
        .equals(other.getFriendId())) return false;
    if (hasFriendProfile() != other.hasFriendProfile()) return false;
    if (hasFriendProfile()) {
      if (!getFriendProfile()
          .equals(other.getFriendProfile())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FRIEND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFriendId().hashCode();
    if (hasFriendProfile()) {
      hash = (37 * hash) + FRIEND_PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getFriendProfile().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateFriendshipRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.UpdateFriendshipRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.UpdateFriendshipRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.UpdateFriendshipRequest)
      POGOProtos.Rpc.UpdateFriendshipRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.UpdateFriendshipRequest.class, POGOProtos.Rpc.UpdateFriendshipRequest.Builder.class);
    }

    // Construct using POGOProtos.Rpc.UpdateFriendshipRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      friendId_ = "";

      if (friendProfileBuilder_ == null) {
        friendProfile_ = null;
      } else {
        friendProfile_ = null;
        friendProfileBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateFriendshipRequest_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateFriendshipRequest getDefaultInstanceForType() {
      return POGOProtos.Rpc.UpdateFriendshipRequest.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateFriendshipRequest build() {
      POGOProtos.Rpc.UpdateFriendshipRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateFriendshipRequest buildPartial() {
      POGOProtos.Rpc.UpdateFriendshipRequest result = new POGOProtos.Rpc.UpdateFriendshipRequest(this);
      result.friendId_ = friendId_;
      if (friendProfileBuilder_ == null) {
        result.friendProfile_ = friendProfile_;
      } else {
        result.friendProfile_ = friendProfileBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.UpdateFriendshipRequest) {
        return mergeFrom((POGOProtos.Rpc.UpdateFriendshipRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.UpdateFriendshipRequest other) {
      if (other == POGOProtos.Rpc.UpdateFriendshipRequest.getDefaultInstance()) return this;
      if (!other.getFriendId().isEmpty()) {
        friendId_ = other.friendId_;
        onChanged();
      }
      if (other.hasFriendProfile()) {
        mergeFriendProfile(other.getFriendProfile());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.UpdateFriendshipRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.UpdateFriendshipRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object friendId_ = "";
    /**
     * <code>string friend_id = 1;</code>
     * @return The friendId.
     */
    public java.lang.String getFriendId() {
      java.lang.Object ref = friendId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string friend_id = 1;</code>
     * @return The bytes for friendId.
     */
    public com.google.protobuf.ByteString
        getFriendIdBytes() {
      java.lang.Object ref = friendId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string friend_id = 1;</code>
     * @param value The friendId to set.
     * @return This builder for chaining.
     */
    public Builder setFriendId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      friendId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string friend_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFriendId() {
      
      friendId_ = getDefaultInstance().getFriendId();
      onChanged();
      return this;
    }
    /**
     * <code>string friend_id = 1;</code>
     * @param value The bytes for friendId to set.
     * @return This builder for chaining.
     */
    public Builder setFriendIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      friendId_ = value;
      onChanged();
      return this;
    }

    private POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friendProfile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder> friendProfileBuilder_;
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     * @return Whether the friendProfile field is set.
     */
    public boolean hasFriendProfile() {
      return friendProfileBuilder_ != null || friendProfile_ != null;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     * @return The friendProfile.
     */
    public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getFriendProfile() {
      if (friendProfileBuilder_ == null) {
        return friendProfile_ == null ? POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.getDefaultInstance() : friendProfile_;
      } else {
        return friendProfileBuilder_.getMessage();
      }
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public Builder setFriendProfile(POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto value) {
      if (friendProfileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        friendProfile_ = value;
        onChanged();
      } else {
        friendProfileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public Builder setFriendProfile(
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder builderForValue) {
      if (friendProfileBuilder_ == null) {
        friendProfile_ = builderForValue.build();
        onChanged();
      } else {
        friendProfileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public Builder mergeFriendProfile(POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto value) {
      if (friendProfileBuilder_ == null) {
        if (friendProfile_ != null) {
          friendProfile_ =
            POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.newBuilder(friendProfile_).mergeFrom(value).buildPartial();
        } else {
          friendProfile_ = value;
        }
        onChanged();
      } else {
        friendProfileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public Builder clearFriendProfile() {
      if (friendProfileBuilder_ == null) {
        friendProfile_ = null;
        onChanged();
      } else {
        friendProfile_ = null;
        friendProfileBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder getFriendProfileBuilder() {
      
      onChanged();
      return getFriendProfileFieldBuilder().getBuilder();
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    public POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder getFriendProfileOrBuilder() {
      if (friendProfileBuilder_ != null) {
        return friendProfileBuilder_.getMessageOrBuilder();
      } else {
        return friendProfile_ == null ?
            POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.getDefaultInstance() : friendProfile_;
      }
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder> 
        getFriendProfileFieldBuilder() {
      if (friendProfileBuilder_ == null) {
        friendProfileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto.Builder, POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder>(
                getFriendProfile(),
                getParentForChildren(),
                isClean());
        friendProfile_ = null;
      }
      return friendProfileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.UpdateFriendshipRequest)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.UpdateFriendshipRequest)
  private static final POGOProtos.Rpc.UpdateFriendshipRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.UpdateFriendshipRequest();
  }

  public static POGOProtos.Rpc.UpdateFriendshipRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateFriendshipRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateFriendshipRequest>() {
    @java.lang.Override
    public UpdateFriendshipRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateFriendshipRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateFriendshipRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateFriendshipRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.UpdateFriendshipRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

