// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

/**
 * Protobuf type {@code POGOProtos.Rpc.UpdateIncomingGameInviteRequest}
 */
public final class UpdateIncomingGameInviteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POGOProtos.Rpc.UpdateIncomingGameInviteRequest)
    UpdateIncomingGameInviteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateIncomingGameInviteRequest.newBuilder() to construct.
  private UpdateIncomingGameInviteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateIncomingGameInviteRequest() {
    appKey_ = "";
    newStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateIncomingGameInviteRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateIncomingGameInviteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            appKey_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            newStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateIncomingGameInviteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateIncomingGameInviteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            POGOProtos.Rpc.UpdateIncomingGameInviteRequest.class, POGOProtos.Rpc.UpdateIncomingGameInviteRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus}
   */
  public enum NewStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>SEEN = 1;</code>
     */
    SEEN(1),
    /**
     * <code>READ = 2;</code>
     */
    READ(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>SEEN = 1;</code>
     */
    public static final int SEEN_VALUE = 1;
    /**
     * <code>READ = 2;</code>
     */
    public static final int READ_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NewStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NewStatus forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return SEEN;
        case 2: return READ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NewStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NewStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NewStatus>() {
            public NewStatus findValueByNumber(int number) {
              return NewStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return POGOProtos.Rpc.UpdateIncomingGameInviteRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final NewStatus[] VALUES = values();

    public static NewStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NewStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus)
  }

  public static final int APP_KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object appKey_;
  /**
   * <code>string app_key = 1;</code>
   * @return The appKey.
   */
  @java.lang.Override
  public java.lang.String getAppKey() {
    java.lang.Object ref = appKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appKey_ = s;
      return s;
    }
  }
  /**
   * <code>string app_key = 1;</code>
   * @return The bytes for appKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppKeyBytes() {
    java.lang.Object ref = appKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEW_STATUS_FIELD_NUMBER = 2;
  private int newStatus_;
  /**
   * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
   * @return The enum numeric value on the wire for newStatus.
   */
  @java.lang.Override public int getNewStatusValue() {
    return newStatus_;
  }
  /**
   * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
   * @return The newStatus.
   */
  @java.lang.Override public POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus getNewStatus() {
    @SuppressWarnings("deprecation")
    POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus result = POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.valueOf(newStatus_);
    return result == null ? POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAppKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appKey_);
    }
    if (newStatus_ != POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.UNSET.getNumber()) {
      output.writeEnum(2, newStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAppKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appKey_);
    }
    if (newStatus_ != POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, newStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof POGOProtos.Rpc.UpdateIncomingGameInviteRequest)) {
      return super.equals(obj);
    }
    POGOProtos.Rpc.UpdateIncomingGameInviteRequest other = (POGOProtos.Rpc.UpdateIncomingGameInviteRequest) obj;

    if (!getAppKey()
        .equals(other.getAppKey())) return false;
    if (newStatus_ != other.newStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAppKey().hashCode();
    hash = (37 * hash) + NEW_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + newStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(POGOProtos.Rpc.UpdateIncomingGameInviteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POGOProtos.Rpc.UpdateIncomingGameInviteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POGOProtos.Rpc.UpdateIncomingGameInviteRequest)
      POGOProtos.Rpc.UpdateIncomingGameInviteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateIncomingGameInviteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateIncomingGameInviteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              POGOProtos.Rpc.UpdateIncomingGameInviteRequest.class, POGOProtos.Rpc.UpdateIncomingGameInviteRequest.Builder.class);
    }

    // Construct using POGOProtos.Rpc.UpdateIncomingGameInviteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      appKey_ = "";

      newStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return POGOProtos.Rpc.POGOProtosRpc.internal_static_POGOProtos_Rpc_UpdateIncomingGameInviteRequest_descriptor;
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateIncomingGameInviteRequest getDefaultInstanceForType() {
      return POGOProtos.Rpc.UpdateIncomingGameInviteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateIncomingGameInviteRequest build() {
      POGOProtos.Rpc.UpdateIncomingGameInviteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public POGOProtos.Rpc.UpdateIncomingGameInviteRequest buildPartial() {
      POGOProtos.Rpc.UpdateIncomingGameInviteRequest result = new POGOProtos.Rpc.UpdateIncomingGameInviteRequest(this);
      result.appKey_ = appKey_;
      result.newStatus_ = newStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof POGOProtos.Rpc.UpdateIncomingGameInviteRequest) {
        return mergeFrom((POGOProtos.Rpc.UpdateIncomingGameInviteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(POGOProtos.Rpc.UpdateIncomingGameInviteRequest other) {
      if (other == POGOProtos.Rpc.UpdateIncomingGameInviteRequest.getDefaultInstance()) return this;
      if (!other.getAppKey().isEmpty()) {
        appKey_ = other.appKey_;
        onChanged();
      }
      if (other.newStatus_ != 0) {
        setNewStatusValue(other.getNewStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      POGOProtos.Rpc.UpdateIncomingGameInviteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (POGOProtos.Rpc.UpdateIncomingGameInviteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object appKey_ = "";
    /**
     * <code>string app_key = 1;</code>
     * @return The appKey.
     */
    public java.lang.String getAppKey() {
      java.lang.Object ref = appKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_key = 1;</code>
     * @return The bytes for appKey.
     */
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      java.lang.Object ref = appKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_key = 1;</code>
     * @param value The appKey to set.
     * @return This builder for chaining.
     */
    public Builder setAppKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppKey() {
      
      appKey_ = getDefaultInstance().getAppKey();
      onChanged();
      return this;
    }
    /**
     * <code>string app_key = 1;</code>
     * @param value The bytes for appKey to set.
     * @return This builder for chaining.
     */
    public Builder setAppKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appKey_ = value;
      onChanged();
      return this;
    }

    private int newStatus_ = 0;
    /**
     * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
     * @return The enum numeric value on the wire for newStatus.
     */
    @java.lang.Override public int getNewStatusValue() {
      return newStatus_;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
     * @param value The enum numeric value on the wire for newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatusValue(int value) {
      
      newStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
     * @return The newStatus.
     */
    @java.lang.Override
    public POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus getNewStatus() {
      @SuppressWarnings("deprecation")
      POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus result = POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.valueOf(newStatus_);
      return result == null ? POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
     * @param value The newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatus(POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      newStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.POGOProtos.Rpc.UpdateIncomingGameInviteRequest.NewStatus new_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatus() {
      
      newStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POGOProtos.Rpc.UpdateIncomingGameInviteRequest)
  }

  // @@protoc_insertion_point(class_scope:POGOProtos.Rpc.UpdateIncomingGameInviteRequest)
  private static final POGOProtos.Rpc.UpdateIncomingGameInviteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new POGOProtos.Rpc.UpdateIncomingGameInviteRequest();
  }

  public static POGOProtos.Rpc.UpdateIncomingGameInviteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateIncomingGameInviteRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateIncomingGameInviteRequest>() {
    @java.lang.Override
    public UpdateIncomingGameInviteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateIncomingGameInviteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateIncomingGameInviteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateIncomingGameInviteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public POGOProtos.Rpc.UpdateIncomingGameInviteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

