// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface UpdateFriendshipRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.UpdateFriendshipRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string friend_id = 1;</code>
   * @return The friendId.
   */
  java.lang.String getFriendId();
  /**
   * <code>string friend_id = 1;</code>
   * @return The bytes for friendId.
   */
  com.google.protobuf.ByteString
      getFriendIdBytes();

  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   * @return Whether the friendProfile field is set.
   */
  boolean hasFriendProfile();
  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   * @return The friendProfile.
   */
  POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto getFriendProfile();
  /**
   * <code>.POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProto friend_profile = 2;</code>
   */
  POGOProtos.Rpc.UpdateFriendshipRequest.FriendProfileProtoOrBuilder getFriendProfileOrBuilder();
}
