// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Rpc.proto

package POGOProtos.Rpc;

public interface WeatherDetailClickTelemetryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POGOProtos.Rpc.WeatherDetailClickTelemetry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameplay_weather_type = 1;</code>
   * @return The gameplayWeatherType.
   */
  java.lang.String getGameplayWeatherType();
  /**
   * <code>string gameplay_weather_type = 1;</code>
   * @return The bytes for gameplayWeatherType.
   */
  com.google.protobuf.ByteString
      getGameplayWeatherTypeBytes();

  /**
   * <code>bool alert_active = 2;</code>
   * @return The alertActive.
   */
  boolean getAlertActive();

  /**
   * <code>.POGOProtos.Rpc.WeatherAlertProto.Severity severity = 3;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.POGOProtos.Rpc.WeatherAlertProto.Severity severity = 3;</code>
   * @return The severity.
   */
  POGOProtos.Rpc.WeatherAlertProto.Severity getSeverity();
}
